### PR TITLE
Add Fanuc.

### PR DESCRIPTION
**Pull request by vcarpani**
For reference, you can see this video: https://www.youtube.com/watch?v=Ft7L5EsF_Kw

### CODE REVIEW

**Comment by hgaiser** [comment]
Doesn't that video say that the order is reversed? So that would be XYZ for Fanuc and ZYX for Kuka?

https://youtu.be/Ft7L5EsF_Kw?t=616

**Comment by vcarpani** [comment]
No, it says that they are the same; I just tested it with a Fanuc robot and got confirmation from a Fanuc robot expert about ZYX

**Comment by hgaiser** [comment]
Hmm yeah okay true it's not reversed like Euler XYZ / ZYX, but does their interface report it as WPR (likewise does a Kuka robot report it as ABC) ? One of the two should be reversed when passing as arguments to this function right?

**Review by hgaiser — APPROVED** [review]

**Comment by de-vri-es** [comment]
> No, it says that they are the same; I just tested it with a Fanuc robot and got confirmation from a Fanuc robot expert about ZYX

Did the expert mention if they were intrinsic or extrinsic rotations though? Because that still causes the order to be flipped without changing the meaning, which sounds exactly like what that movie suggests.

**Comment by de-vri-es** [comment]
Ah, but that is mentioned in the comments.

**Comment by de-vri-es** [comment]
But why does conversion to angles give `(W, P, R)`, but conversion from angles want `(R, P, W)`? That does not seem consistent to me.

**Comment by vcarpani** [comment]
> But why does conversion to angles give `(W, P, R)`, but conversion from angles want `(R, P, W)`? That does not seem consistent to me.

Indeed it is not, might refactor it later, but this works for now as code example

**Pull request merged**
